export const BANCOS = [
  { value: 'bbva', label: 'BBVA México' },
  { value: 'banorte', label: 'Banorte' },
  { value: 'santander', label: 'Santander' },
  { value: 'banamex', label: 'Citibanamex' },
  { value: 'hsbc', label: 'HSBC' },
  { value: 'scotiabank', label: 'Scotiabank' },
  { value: 'inbursa', label: 'Inbursa' },
  { value: 'banregio', label: 'Banregio' },
  { value: 'bajio', label: 'Banco del Bajío' },
  { value: 'afirme', label: 'Afirme' },
  { value: 'mifel', label: 'Mifel' },
  { value: 'multiva', label: 'Multiva' },
  { value: 'azteca', label: 'Banco Azteca' },
  { value: 'bancoppel', label: 'BanCoppel' },
  { value: 'compartamos', label: 'Banco Compartamos' },
  { value: 'famsa', label: 'Banco Famsa' },
  { value: 'invex', label: 'Invex' },
  { value: 've-por-mas', label: 'Ve por Más' },
  { value: 'monex', label: 'Monex' },
  { value: 'autofin', label: 'Banco Autofin' },
  { value: 'hey-banco', label: 'Hey Banco' },
  { value: 'nu', label: 'Nu México' },
  { value: 'klar', label: 'Klar' },
  { value: 'stori', label: 'Stori' },
  { value: 'otro', label: 'Otro' },
]
